# Generated by Django 4.2.9 on 2024-01-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201007_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetResultModel',
        ),
    ]
