# Generated by Django 4.1.3 on 2024-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_tweetresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
